/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AktuellesPost: typeof import('./components/AktuellesPost.vue')['default']
    AngebotItem: typeof import('./components/AngebotItem.vue')['default']
    AngebotSection: typeof import('./components/AngebotSection.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ContactForm: typeof import('./components/ContactForm.vue')['default']
    ContactSection: typeof import('./components/ContactSection.vue')['default']
    FooterSection: typeof import('./components/FooterSection.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroSection: typeof import('./components/HeroSection.vue')['default']
    Kursplan: typeof import('./components/Kursplan.vue')['default']
    KursplanSection: typeof import('./components/KursplanSection.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamMemberItem: typeof import('./components/TeamMemberItem.vue')['default']
    TeamSection: typeof import('./components/TeamSection.vue')['default']
  }
}
